services:
  service-a:
    build: ./service_a
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - SERVICE_B_URL=http://service-b:8081/weather
  service-b:
    build: ./service_b
    environment:
      - WEATHERAPI_KEY=54619d224b96477a9d420100262101
      - PORT=8081
